language: generic
sudo: false
dist: trusty
branches:
  only:
  - master
addons:
  apt:
    packages:
    - curl
    - gettext
    - python3-pip
    - jq
    - git
install:
  - pip3 install yq
script:
- "./build"
- sudo ./build install
deploy:
  provider: releases
  file_glob: true
  file: firefoxdev_*_amd64.deb
  skip_cleanup: true
  api_key:
    secure: hG0OxEVDFBXJP4d+U0Zwm6a8lp3Qa0PRlrvbLyDDWFHg5lJ/Z0fCCYXgU+VxEfYL/F/7uIz2pKoV6d5+Na6vf4DvwthRzhGwnOf6OR2U6880xr2qmXoXn2365lR0BQDN3LMcnkPs53KdLY1ymqwuc3EAX8EWKLocUpRCWv7VMHmjU/xfiFS5Joq0MiQh1yoPnMgaRrPtcnhEunLNHzKSJXthKbZu6PTwD7ZKrW+0CEWUBNoCol8BbY9bPXMG+n1HrV1xwTmQZ9WVaaY0/63AsI756ltAt2K9XTcRo1DYtPQ9ZDMlbZ6GDm17SsGUpTfA57DUEzVPJbTP7Qsi9ml1/VjhY5lAKVq7fO4amKyfKCvr/EhscDlXdJoSHk8jKlQa9cl0mqSXGPobdB8aL4ozfB9fdvKpD2/6QncLPGXcWpEJf867I42OvbYrEtJw/SDyc/U8sItSBs4hwFX2E2CYIMoXfdZLXaDmTJjHXP/HcfmVtvhJTueRvA6bxCQcZW9C8PwwrAJTVmSxTxYnV72QUtg5vBJA4DWsGOjRivVLoPzoL6J3rRZnvRTAhnZD7/atunkEhEz5alRyGU4zzWp3wmsQJlRg6r9SEeRJ6aZPDvY170CHrnWEiW3WUoKlwynKNZYw1PFELNSVmEVe/2y4VyCg/LdJzBLne7dlCRSSn5E=
  verbose: true
  on:
    tags: true
