language: generic
sudo: false
dist: trusty
branches:
  only:
  - master
addons:
  apt:
    packages:
    - curl
    - gettext
    - python3-pip
    - jq
    - git
install:
  - sudo pip3 install yq
script:
  - "./build"
  - sudo ./build install
deploy:
  provider: releases
  file_glob: true
  file: firefoxdev_*_amd64.deb
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  verbose: true
  on:
    tags: true
env:
  secure: Jq0V/VI9bhZl4uaMLjqZDtpyBSOAS8BVjCDfrGJQyV5rBN2OVXb6wtF3vCgivly5ZRy+dTtmlL1HWNBqYVUg6uAzfO4USSViQgBlFZ+dkXWDuWRYoVhqH8oaFoFXTJcTA1/e6PLGngK6mvwXjtaMceVSy7iDVO5OA4Wmhqa0S/P6Ti0QK41UtkRypyDFR+yBFe9F3FCh+fa0bC+7KA6xfuO9fG/jPzMDi93HAVXQFdiHL86frGQ9qcMXbJ98VV33/FzgDbhbZZnxSWVfQfhe0f6ZrfD9UrEdCPH23F61dwjcFbez4vLR0Ire0ytBuIBUzVXucN6wVmPACbVeUoMFLXxuLAy7SHKaefSnUUT4zfz/FBm2TAWIOOTy/qL84dFuY+vD0Own+LX+0EBrUMITBovjohY0Pm1h5PWT9LoHeZF2CQ3bbQjEt4Jf/LHFUQrY0m6L2dj/cyJT/O6hsUXlglT0F0SuPyaceW9leURyPh7jRMY3k/ihQzjY8WGvGqU1URXlCQZPwXtuT+PLixm5FZmtjrhcDm5zXkGI0NCxlYJ2wK5eQx7ZGLImtS+rW7sETPtg3FfQ43nvXSFTT3gcgPQhCJmFNJFFspwDaNHkPyepe8/QMaZ4X8WF61B/S1Hq02Van0zEo1rYODExPR/N8TnaNlSB2b0EKu8Yr3wkwFI=
