language: generic
sudo: false
dist: trusty
branches:
  only:
  - master
addons:
  apt:
    packages:
      - curl
      - gettext
install:
  - sudo apt-get update && sudo apt-get upgrade -y
script: 
  - ./build
  - sudo ./build install
deploy:
  provider: releases
  file_glob: true
  file: firefoxdev_*_amd64.deb
  skip_cleanup: true
  api_key: "$GITHUB_TOKEN"
  verbose: true
  on:
    tags: true
